### PR TITLE
BDB RF Configs Beta

### PR DESCRIPTION
**Pull request by Bellabong**
Cleaned everything up, this pull request should just be the BDB configs. Should work out of the box but just needs balancing.

### CODE REVIEW

**Comment by ValentinBischof** [comment]
Im sorry, very busy this week haven’t had any time to test yet, may get to that this weekend.
Just a quick question, why did you disable the engineSwitch remover? These don’t affect the mesh ones. The B9PartSwitch Modules that change the mesh go under the `moduleID = meshSwitcher`, the one that change the engine stats (isp, thrust) go under `moduleID = engineSwitcher`, which only the patch targets.
Maybe I’m just missing something here.

**Comment by Bellabong** [comment]
Due to issues I encountered with SRBs, there are some that use engineswitch to adjust the amount of resources (specifically solid fuel). This is actually a good thing as it should be possible to patch the amount of SolidFuel that BDB adds and SolidFuel tanks is the only thing that RF doesn't need to manage. 

BDB pretty much uses engineswitch for everything. The ones that switch nozzles (such as the Agena XLR81) look like

```
MODULE
	{
		name = ModuleB9PartSwitch
		switcherDescription = Engine Config
		switcherDescriptionPlural = Engine Configs
		moduleID = engineSwitch

		SUBTYPE
		{
			name = engine1
			transform = engine1
		}

		SUBTYPE
		{
			name = engine2
			transform = engine2
		}

```
The effect of disabling the engine parts switch module entirely is that it loads all the transforms at the same time for these engines and all the newest engines are set up like this (Thor/Delta LR79, Agena XLR81, the brand spanking new RL10) so I've disabled it as that's an unwanted side-effect.

**Comment by ValentinBischof** [comment]
Aah, i see, that's a bummer. If it's just small change of the mesh (nozzle size, nozzle extension), i can live without them. Its better than having these Warning on startup & having parts that do have these engineSwitcher, without changing mesh on all of them (as not every engineSwitcher changes mesh, but only some, which can be very confusing for some)

**Comment by Bellabong** [comment]
Yeah I thought I could just shift the configs for the larger bell XLR81 to the 8096C. 

The warnings come from 

```
		SUBTYPE
		{
			name = engine1
			transform = engine1

			MODULE
			{
				IDENTIFIER
				{
					name = ModuleEnginesFX
				}

				DATA
				{
					atmosphereCurve
					{

					}
				}
			}
		}
```
wanting to edit the nonexistent engine, if a patch could be made to remove [MODULE] from each subtype the warnings should disappear and the mesh and resource switching for SRBs should be unaffected.

**Comment by ValentinBischof** [comment]
This untested patch should delete the Module in a Subtype

```

@PART[bluedog*,Bluedog*]:HAS[@MODULE[ModuleB9PartSwitch]:HAS[#moduleID[engineSwitch],@SUBTYPE:HAS[@MODULE:HAS[@IDENTIFIER[ModuleEngineFX]]]] 
{
  @MODULE[ModuleB9PartSwitch]:HAS[#moduleID[engineSwitch]]
  {
    @SUBTYPE:HAS[@MODULE:HAS[@IDENTIFIER[ModuleEnginesFX]]],*
    {
      !MODULE:HAS[@IDENTIFIER[ModuleEnginesFX]] {}
    }

  }
  
}
```
The only problem that would still exist is that in case of the RL10, you have 3 variants, only one of them change mesh, which means you have 2 variants that don’t change anything when selected, but only one changes something
These will probably have to deleted manually, each by one patch.

But moving them just to other engines, is a really good idea for engine where this is possible.

**Comment by Bellabong** [comment]
Figured out a patch to fix the partswitcher errors but uploaded before I saw your more refined version. 

I'll probably change the descriptions of each engineconfig as well as B9 description to say which bell is associated with which engine once I start removing the extra B9 subtypes because that's a better for general release. I've already added alternate configs which assume the previous configs engine bell so I have to do that anyway.

A fun idea would be to have B9 bell switching affect the lsp and engineconfig the other stats. Would be possible if engineconfigs lsp could be turned into a multiplier which would support lsp improvement through different fuels.

**Comment by ValentinBischof** [comment]
> A fun idea would be to have B9 bell switching affect the lsp and engineconfig the other stats. Would be possible if engineconfigs lsp could be turned into a multiplier which would support lsp improvement through different fuels.

Oooh, that's hell of a good idea, so basically If I understand right, fuel switching & engine "switching" is done by RF and the different B9PartSwitch Meshes are just giving the RF Config an extra boost in ISP and/or thrust dependent on what the mesh switcher changes? (nozzle size, etc...) 
Not sure if this is compatible together, when choosing an Config through RF and then editing the ModuleEnginesRF to give it better ISP and/or thrust.

**Comment by Bellabong** [comment]
It should be doable if the atmospherecurve section can be omitted in each engine config so B9 alone handles the lsp entries.

Although this could apply to other mods this would only really apply to the Agena and Centaur with the Agena having fuel configs that should affect lsp as well and I dont see how to make that work.

**Comment by Bellabong** [comment]
I think that should be it, everything should work as intended. 

Are
			IspSL = 1.0000
			IspV = 1.0000

under other engine configs I've looked through multipliers? If so then it should be possible to make the idea work because RF applies it's thrust multipliers for example on top of whatever stats B9 sets if MODULE references ModuleEnginesRF.

**Comment by ValentinBischof** [comment]
> I think that should be it, everything should work as intended.

First, thank you so much for all the work you've done on this. Just tell me when I should merge this.

> Are
> IspSL = 1.0000
> IspV = 1.0000
under other engine configs I've looked through multipliers? If so then it should be possible to make the idea work because RF applies it's thrust multipliers for example on top of whatever stats B9 sets if MODULE references ModuleEnginesRF.

Yes these are multipliers, IspSL for SeaLevel Isp and V for Vacuum Isp. I think that only `ModuleEngineConfigs` can set those values, not ModuleEnginesRF (not sure about this), so either, (if working) the IspSL & IspV Multipliers or the atmosphere curve

**Comment by Bellabong** [comment]
I just encountered a massive bug that I can't figure out - when an SRB is configured by the configs and has the solid-vacuum realplume config in BDB the engine has no fuel flow whether it has SolidFuel in ModuleFuelTanks or just as a resource (and doesn't thrust of course). At first I thought it was something to do with with BDB's flat thrust curve but luckily I accidentally configured a seperation SRB and it had the flat thrust curve, a solidfuel based EnginesRF but it had the solid-sepmotor config and fired normally. SRB's that aren't configured by RF but have the solid-vacuum effect and flat thrust curve fire normally so I'm at a loss as to why the SRBs look fine in the editor and in flight up until ignition. I've tried various configs and the common denominator are engines with solid-vacuum as their RealPlume config. 

If this bug is fixed I can confidently say every engine fires as intended. If this is some deeper RealFuels bug then I can just comment out the SRB engine configs and let B9 handle the engine performance for those parts. BDB is balanced to 2.5x scale anyway so it'd just be a matter of exluding the relevant SRBs from the EngineSwitch disabler.

**Comment by Bellabong** [comment]
That should be a set of configs that doesn't have any game-breaking elements so I wont be committing for a while I work on features and not constant fixes. All LF engines should be configured, Atlas and Centaur tanks are Balloon or Ballooncryo respectively and engine types should unlock at the same time the B9 config should be available.

**Comment by Bellabong** [comment]
So when it comes to B9 tanks the patch I've come up with looks a little something like

```
@PART[bluedog_Vanguard_S2_Tank]:FOR[RealFuels]
{	
	@MODULE[ModuleB9PartSwitch]:HAS[#moduleID[volumeSwitch]]
	{
		@SUBTYPE,0
		{
			MODULE
			{
				IDENTIFIER
				{
					name = ModuleFuelTanks
				}
				DATA
				{
					volume = 325
					TANK
					{
						name = Hydrazine
						amount = full
						maxAmount = 7.6923076923%

					}
					TANK
					{
						name = UDMH
						amount = full
						maxAmount = 41.6448535%
					}
					TANK
					{
						name = IRFNA-III
						amount = full
						maxAmount = 50.6628388077%
					}
				}
			}
		}
        
		@SUBTYPE,1
		{
			!volumeAddedToParent
            
		MODULE
		{
			IDENTIFIER
			{
				name = ModuleFuelTanks
			}
			DATA
			{
				volume = 625
					TANK
					{
						name = Hydrazine
						amount = full
						maxAmount = 4%

					}
					TANK
					{
						name = UDMH
						amount = full
						maxAmount = 43.31064764%
					}
					TANK
					{
						name = IRFNA-III
						amount = full
						maxAmount = 52.68935236%
					}
			}
 		}
	}
}

@PART[bluedog_Vanguard_S1_Tank]:FOR[RealFuels]
{	
	@MODULE[ModuleB9PartSwitch]:HAS[#moduleID[volumeSwitch]]
	{
		@SUBTYPE,0
		{
			MODULE
			{
				IDENTIFIER
				{
					name = ModuleFuelTanks
				}
				DATA
				{
				volume = 2450

					TANK
					{
						name = Kerosene
						amount = full
						maxAmount = 38.0018572131%
					}
					TANK
					{
						name = LqdOxygen
						amount = full
						maxAmount = 61.9981427869%
					}
				}
			}
		}
        
		@SUBTYPE,1
		{
			!volumeAddedToParent
            
		MODULE
		{
			IDENTIFIER
			{
				name = ModuleFuelTanks
			}
			DATA
			{
				volume = 4000

				TANK
				{
					name = Kerosene
					amount = full
					maxAmount = 38.0018572131%
				}
				TANK
				{
					name = LqdOxygen
					amount = full
					maxAmount = 61.9981427869%
				}
			}
 		}
	}
}`
```

The state things are in at the moment is that no matter what B9 seems to nuke the resources and that's what that pull request I mentioned earlier is supposed to fix.

There is a workaround for now without just setting the tank size to max/clipping in tanks though - sub-assemblies "remember" their volume so a set of sub assemblies could be provided with the appropriate volume size. This only involves 5 parts or so and only one of them is necessary (The Thor/Delta tank).

**Comment by Bellabong** [comment]
So the idea about having B9 and RF interact with the Bell and Fuel Type both affecting the nozzle works. I don't see a situation where you'd combine a "worse" vacuum nozzle with better fuel though - except for take-offs from Eve I guess but I don't see the XLR81 or RL10 doing that though and this kind of flexibility is better applied once the engines have more fuel configs.

**Comment by ValentinBischof** [comment]
Ouuh, that B9PS thingy works? Didn't thought so, but this is really cool.

Im a bit inactive right now, on vacations right now, with very bad internet connection. 

Already saw your commit for the first release candidate, does that mean as soon as I'm back (and allowed to merge this) can I already merge this to master for the next RF-Stock release?

**Comment by ValentinBischof** [comment]
Back from my holidays, what's the status on this? Im still seeing you're committing (thank you so much again!) and I wanna ask if it's already something for the next release? Took a small peak into this and what I can say is this is awesome.

**Comment by Bellabong** [comment]
It's pretty much ready for release, minor balance tweaks (current Hydrox fuel cell rates are balanced to 24/h) and the solid-vacuum issue aside I feel it's ready for release. Probably need to start working on making things cost money but it's very usable at 2.5x and at 3.2x with the techlevel upgrades.

**Comment by ValentinBischof** [comment]
I'm really unsure of how to thank you for this, this is great. I really appreciate! If you have any changes, just create a new PR. 
And again many thanks!

**Pull request merged**
